A = [0 -1; -3 2];
B = [1 2; 5 3];
M = [1 -1 0 -1 0; 1 0 3 0 2];
inv_A = inv(A);
inv_B = inv(B);
disp('Inverse of A:');
disp(inv_A);
disp('Inverse of B:');
disp(inv_B);
AB = A * B;
inv_AB = inv(AB);
disp('Inverse of AB:');
disp(inv_AB);
inv_BA = inv(B) * inv(A);
disp('inv(B) * inv(A):');
disp(inv_BA);
C = inv(B) * M;
BC = B * C;
disp('C = inv(B) * M:');
disp(C);
disp('BC = B * C:');
disp(BC);
